
usr/share/doc/minetest/*             usr/share/doc/minetest/
usr/share/games/minetest/builtin/*   usr/share/games/minetest/builtin
usr/share/games/minetest/client/*    usr/share/games/minetest/client
usr/share/games/minetest/games/*     usr/share/games/minetest/games
usr/share/games/minetest/textures/*  usr/share/games/minetest/textures
usr/share/games/minetest/fonts
usr/share/locale
usr/share/icons/hicolor/scalable/apps/minetest.svg
usr/share/appdata/minetest.appdata.xml